// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type OmsCampaign struct {
	ID        int32
	Name      string
	StartedAt sql.NullTime
	EndedAt   sql.NullTime
	Archiving sql.NullBool
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type OmsCampaignLineItem struct {
	ID          int32
	CampaignID  int32
	Name        string
	Booked      string
	Actual      sql.NullString
	Adjustments sql.NullString
	StartedAt   sql.NullTime
	EndedAt     sql.NullTime
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type OmsInvoice struct {
	ID                int32
	CampaignID        int32
	TotalBookedAmount sql.NullString
	TotalActualAmount sql.NullString
	TotalAdjustments  sql.NullString
	StartedAt         sql.NullTime
	EndedAt           sql.NullTime
	IssuedAt          sql.NullTime
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
}
